kind: Service
apiVersion: v1
metadata:
  name: tetris
  labels:
    app: tetris
spec:
  selector:
    app: tetris
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  labels:
    app: tetris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      nodeSelector:
        team: devops
      containers:
      - name: tetris
        image: theologian/tetris:v0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
